workflows:
  ios-workflow:
    name: iOS Build
    instance_type: mac_mini
    environment:
      flutter: stable
    script:
      - name: Flutter build
        script: flutter build ios --no-codesign
