workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    scripts:
      - name: Flutter build
        script: |
          flutter pub get
          flutter build ios --no-codesign
      - name: Create IPA
        script: |
          cd build/ios/Release-iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload
          zip -r app.ipa Payload
          mv app.ipa ../../../
    artifacts:
      - app.ipa
